// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSBATbJ0Qi1UJtgCGPJjqT45GzDhbs9M',
    appId: '1:854327117508:web:bc565e23e771052913ab91',
    messagingSenderId: '854327117508',
    projectId: 'gradsnap-d1f21',
    authDomain: 'gradsnap-d1f21.firebaseapp.com',
    storageBucket: 'gradsnap-d1f21.firebasestorage.app',
    measurementId: 'G-6ZY1ZGPF9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdhWjSYyyVYdwByr33LcdRtwSTsc31yc',
    appId: '1:854327117508:android:90abe96e1d82bee113ab91',
    messagingSenderId: '854327117508',
    projectId: 'gradsnap-d1f21',
    storageBucket: 'gradsnap-d1f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nkO1JiouaR_cIkgccZNBYPAGlBfzXHQ',
    appId: '1:854327117508:ios:fa75f87afc86337c13ab91',
    messagingSenderId: '854327117508',
    projectId: 'gradsnap-d1f21',
    storageBucket: 'gradsnap-d1f21.firebasestorage.app',
    androidClientId: '854327117508-hkl68013bl8o5636kfk7s9vts756kkdt.apps.googleusercontent.com',
    iosClientId: '854327117508-0u3bfhtetb53qts9ulf7c3h9vrhkag18.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6nkO1JiouaR_cIkgccZNBYPAGlBfzXHQ',
    appId: '1:854327117508:ios:fa75f87afc86337c13ab91',
    messagingSenderId: '854327117508',
    projectId: 'gradsnap-d1f21',
    storageBucket: 'gradsnap-d1f21.firebasestorage.app',
    androidClientId: '854327117508-hkl68013bl8o5636kfk7s9vts756kkdt.apps.googleusercontent.com',
    iosClientId: '854327117508-0u3bfhtetb53qts9ulf7c3h9vrhkag18.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSBATbJ0Qi1UJtgCGPJjqT45GzDhbs9M',
    appId: '1:854327117508:web:42fd1cfe6493492f13ab91',
    messagingSenderId: '854327117508',
    projectId: 'gradsnap-d1f21',
    authDomain: 'gradsnap-d1f21.firebaseapp.com',
    storageBucket: 'gradsnap-d1f21.firebasestorage.app',
    measurementId: 'G-EBQNG3ZEDY',
  );
}
